server:
  port: 8080
spring:
  jpa:
    show-sql: false       # 打印当前所执行的SQL
    open-in-view: false   # 关掉该选项可以避免会话一直挂着，提升性能
    hibernate:
      ddl-auto: update    # 数据库定义语句自动模式：create, create-drop, update, validate
  data:
    redis:
      host: ${admax.datasource.redis.host}
      port: ${admax.datasource.redis.port}
      database: 0
      timeout: 10s
      lettuce:
        pool:
          max-active: 200
          max-wait: -1ms
          min-idle: 1
          max-idle: 10
logging:
  config: classpath:logback-spring.xml
  # 日志级别 FATAL > ERROR > WARN > INFO > DEBUG > TRACE
  level:
    root: INFO
    org.springframework: WARN
    org.springframework.boot.web.embedded: INFO
    org.apache: WARN
    fun.xianlai.admax: INFO
