server:
  port: 8080
spring:
  sql:
    init:
      mode: always                          # 启用sql初始化模式
      data-locations: classpath:data.sql    # 用于初始化写入数据的sql文件
      continue-on-error: false
  jpa:
    show-sql: false                         # 打印当前所执行的SQL
    open-in-view: false                     # 关掉该选项可以避免会话一直挂着，提升性能
    hibernate:
      ddl-auto: update                      # 数据库定义语句自动模式：create, create-drop, update, validate
    defer-datasource-initialization: true   # 初始化文件data.sql在JPA建表后再执行
logging:
  config: classpath:logback-spring.xml
  # 日志级别 FATAL > ERROR > WARN > INFO > DEBUG > TRACE
  level:
    root: INFO
    org.springframework: WARN
    org.springframework.boot.web.embedded: INFO
    org.apache: WARN
    fun.xianlai.admax: INFO
